### ISSUE TITLE
 'thread.lock' object has no attribute 'lock'

### ISSUE THREAD

**Issue by yannh** [lucidsoftware/apt-boto-s3#1]
Hello! The project looks super interesting, sadly I am not getting it to work...

yann@ubuntu:~/$ sudo apt-get update
0% [Working]Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/lib/apt/methods/s3", line 76, in handle_message
    with interrupt_lock.lock():
AttributeError: 'thread.lock' object has no attribute 'lock'

Thanks for the effort!

**Comment by pauldraper** [comment]
I fixed the issue in 2a9cf07613f31f428f5eb6a6e75ebc0eb10f8e0c

Unfortunately, that was an issue in error reporting. That means you still have an problem, though now you'll get a better error.

**Comment by yannh** [comment]
Hi Paul, yes, I guess it has to do with SIGV4 -> https://github.com/boto/boto/issues/2741
I d totally buy you a beer if you get it to work in Frankfurt :)

**Comment by pauldraper** [comment]
@yannh, you should be able to fix that by adding a [boto config file](http://boto.cloudhackers.com/en/latest/boto_config_tut.html) as described in https://github.com/boto/boto3/issues/329

E.g. in ~/.aws/credentials

```
[default]
s3 =
    signature_version = s3v4
```

I would like to change apt-boto-s3 to fix this automatically, but I belive this has implications for what URL styles are acceptable (I think it needs to be path style?). I will research this.

**Comment by pauldraper** [comment]
Related to #1
