### ISSUE TITLE
The repository 'http://dl.bintray.com/lucidsoftware/apt lucid Release' is no longer signed.

### ISSUE THREAD

**Issue by erkki** [lucidsoftware/apt-boto-s3#17]
It seems like the apt repository for apt-boto-s3 is no longer signed

**Comment by pauldraper** [comment]
It appears to be correct to me. Please describe otherwise.

**Comment by erkki** [comment]
This was a while ago, I can't confirm/deny anymore so fine to close if it seems to be working on your end.
