### ISSUE TITLE
Package apt-boto-s3 doesn't seem to exist in any lucidsoftware repository

### ISSUE THREAD

**Issue by witchbutter** [lucidsoftware/apt-boto-s3#18]
I have added a sources.list file as specified to point to 'deb http://dl.bintray.com/lucidsoftware/apt/ main contrib' exactly as described on github but no package or metapackage named apt-boto-s3 is found.  I downloaded several Packages files and examined the contents and apt-boto-s3 doesn't seem to be in any of them, whether its main contrib or trusty main or xenial main etc.

**Comment by mconigliaro** [comment]
The README says to use `lucid main` (not `main contrib`):

    deb http://dl.bintray.com/lucidsoftware/apt/ lucid main
