### ISSUE TITLE
v4 considerations

### ISSUE THREAD

**Issue by pauldraper** [lucidsoftware/apt-boto-s3#2]
We should either document the workaround (https://github.com/boto/boto3/issues/329) or make the code use v4 all the time. This latter one may affect what URLs are acceptable.

Related to #1

**Comment by yannh** [comment]
Maybe this can help:
https://github.com/aws/aws-cli/blob/592e32d9fb46addaf640deb8e403b1e9ffbdd025/awscli/topics/s3-faq.rst

. The AWS CLI will use Signature Version 4 for S3 in several cases:
    You're using an AWS region that only supports Signature Version 4. This includes eu-central-1 and ap-northeast-2.
    You explicitly opt in and set signature_version = s3v4 in your ~/.aws/config file.

Maybe it would be conceivable to do whitelisting?

**Comment by pauldraper** [comment]
The default signing behavior should [just work](https://github.com/lucidsoftware/apt-boto-s3/tree/839a18d929c0eb31d6703042b231fd2ba4a1c099#signature-version) now. And users can override that if necessary.
