### ISSUE TITLE
Since installing, dpkg/apt locaks are always held.  

### ISSUE THREAD

**Issue by pbeeson** [lucidsoftware/apt-boto-s3#25]
Since installing, on ALL Ubuntu 16.04 machines that use this, the various locks regarding package installation are always being help by process `python2 /usr/lib/apt/methods/s3`.

```
sudo apt-get update
Reading package lists... Done
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
```
```
sudo pkill -9 python2
sudo apt-get update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
...
```

**Comment by pbeeson** [comment]
Basically if you run `/usr/lib/apt/methods/s3`, you cannot even CTRL-C out of it.

**Comment by ana-GT** [comment]
Following up on Patrick's report: I observe the same described issue in 2 different machines (running Ubuntu 16.04).

**Comment by pbeeson** [comment]
Closing since support was never provided.
