### ISSUE TITLE
Random threading issues

### ISSUE THREAD

**Issue by yannh** [lucidsoftware/apt-boto-s3#7]
I randomly get this error:

Exception in thread Thread-3:  
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/lib/apt/methods/s3", line 87, in handle_message
    self._send_error(ex)
  File "/usr/lib/apt/methods/s3", line 57, in _send_error
    self.send(Message(MessageHeaders.GENERAL_FAILURE, (('Message', message),)))
  File "/usr/lib/apt/methods/s3", line 54, in send
    self.pipes.output.flush()
IOError: [Errno 32] Broken pipe

The more other APT repositories configured, the less likely it is to fail. If the s3 repo is the only repository configured, then it works nearly every time. If i reenable the rest of the sources.list, if fails nearly every time (but still works sometimes).

**Comment by pauldraper** [comment]
I noticed some issues too.

Apt set up the API so that it looks like multiplexing is fine. But it appears that they really do require pipelining (responses in the same order as the requests).

I'll try fixing that first, and we'll see if those go away.

**Comment by pauldraper** [comment]
I released [1.1](https://bintray.com/lucidsoftware/apt/apt-boto-s3/1.1). See if it works any better.

**Comment by yannh** [comment]
Seems to work reliably now! :+1:
